apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - nodePort: 30100
      port: 80
      targetPort: 80
